# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-10 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0030_election_candidates_can_commit_everywhere'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('candidates', models.ManyToManyField(related_name='groups', to='elections.Candidate')),
            ],
        ),
    ]
