# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-02 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/profiles/', verbose_name='Tu imagen de perfil')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tu descripci\xf3n')),
                ('first_time_in_backend_citizen', models.BooleanField(default=False)),
                ('is_organization', models.BooleanField(default=False)),
                ('is_journalist', models.BooleanField(default=False)),
                ('unsubscribed', models.BooleanField(default=False, verbose_name='No quiero recibir noticias sobre las propuestas que me gustan')),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
