# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0001_initial'),
        ('backend_citizen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='popolo.Organization')),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('popolo.organization',),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='backend_citizen.Organization'),
        ),
    ]
