# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-07 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_citizen', '0001_initial_squashed_0003_auto_20160426_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organization', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/profiles/', verbose_name='Tu imagen de perfil')),
                ('description', models.TextField(verbose_name='Tu descripci\xf3n')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
