# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0001_initial'),
        ('backend_citizen', '0002_auto_20160426_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_ptr',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
