# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_citizen', '0003_auto_20160712_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_time_in_backend_citizen',
            field=models.BooleanField(default=False),
        ),
    ]
