# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_citizen', '0004_profile_first_time_in_backend_citizen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_organization',
        ),
    ]
