# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_citizen', '0005_remove_profile_is_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
    ]
