# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_citizen', '0007_profile_is_journalist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tu descripci\xf3n'),
        ),
    ]
