# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 18:22
from __future__ import unicode_literals

from django.db import migrations
import uuid


def create_unsubscribe_token_for_profile(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Profile = apps.get_model('backend_citizen', 'Profile')
    for profile in Profile.objects.all():
        profile.unsubscribe_token = uuid.uuid4()
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend_citizen', '0009_auto_20171005_1822'),
    ]

    operations = [
    migrations.RunPython(create_unsubscribe_token_for_profile),
    ]
