# coding=utf-8
from django.utils.translation import ugettext as _

_TOPIC_CHOICES = (('', _(u'Selecciona una categoría')),
                 (u"politica-metropolitana", u"Política Metropolitana"),
                 (u"emprego-renda", u"Emprego & Renda"),
                 (u"moradia", u"Moradia "),
                 (u"mobilidade-urbana", u"Mobilidade Urbana"),
                 (u"seguranca-publica", u"Segurança Pública"),
                 (u"saneamento-basico", u"Saneamento Básico"),
                 (u"saude", u"Saúde"),
                 (u"idoso", u"Idoso"),
                 (u"educacao", u"Educação"),
                 (u"cultura", u"Cultura"),
                 (u"espacos-publicos", u"Espaços Públicos"),
                 (u"meio-ambiente", u"Meio Ambiente  "),
                 (u"direitos-humanos", u"Direitos Humanos"),
                 (u"justica-racial", u"Justiça Racial "),
                 (u"equidade-genero", u"Equidade de gênero"),
                 (u"direitos-lgbt", u"Direitos LGBTQI+"),
                 (u"politica-tributaria", u"Política Tributária"),
                 (u"gestao-publica", u"Gestão Pública, transparência e participação"),
                 (u"sistema-politico", u"Sistema Político"),
                 (u"transparencia-participacao-e-sistema-politico", u"Transparência, Participação e Sistema Político "),
                 (u"juventude", u"Juventude"),
                 (u"infancia", u"Infância"),
)
