# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-02 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('url', models.URLField(blank=True, null=True)),
                ('location', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('long_description', models.TextField(blank=True)),
                ('contact_info', models.TextField(help_text='Aqu\xed puedes escribir un n\xfamero telef\xf3nico, un email o un whatsapp.', verbose_name='C\xf3mo te pueden contactar las personas interesadas?')),
                ('important', models.BooleanField(default=False, verbose_name='Es este evento importante?')),
                ('background_image', models.ImageField(blank=True, help_text='ser\xe1 la imagen que utilicemos en la lista de eventos', null=True, upload_to='agenda/activities/', verbose_name='Una imagen para el evento')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('object_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['date'],
            },
            managers=[
                ('futures', django.db.models.manager.Manager()),
            ],
        ),
    ]
