# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='activity',
            name='background_image',
            field=models.ImageField(blank=True, help_text='ser\xe1 la imagen que utilicemos en la lista de eventos', null=True, upload_to='agenda/activities/', verbose_name='Una imagen para el evento'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='activity',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
