# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-02 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20180502_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='long_description',
            field=models.TextField(blank=True),
        ),
    ]
