# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_activity_long_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activity',
            managers=[
                ('futures', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='contact_info',
            field=models.TextField(default='Contact info', help_text='Aqu\xed puedes escribir un n\xfamero telef\xf3nico, un email o un whatsapp.', verbose_name='C\xf3mo te pueden contactar las personas interesadas?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Es este evento importante?'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
