# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-05 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20180525_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date']},
        ),
    ]
