# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0025_auto_20160701_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='position',
            field=models.CharField(blank=True, default=b'', help_text='A qu\xe9 cargo est\xe1 postulando?', max_length=255, null=True),
        ),
    ]
