# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0027_auto_20160818_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='value',
            field=models.CharField(max_length=4096),
        ),
    ]
