# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-24 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0028_auto_20160913_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='has_won',
            field=models.BooleanField(default=False),
        ),
    ]
