# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 21:23
from __future__ import unicode_literals

from django.db import migrations, models


def copy_id_into_slug(apps, schema_editor):
    Candidate = apps.get_model('elections', 'Candidate')
    for candidate in Candidate.objects.all():
        candidate.slug = candidate.id
        candidate.save()
def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0031_election_second_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='slug',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(copy_id_into_slug, reverse_code=reverse),
    ]   
