# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-03 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0033_auto_20180717_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='extra_info_content',
            field=models.TextField(blank=True, help_text='Voc\xea pode usar Markdown. <br/> <a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a> allowed, but no raw HTML. Examples: **bold**, *italic*, indent 4 spaces for a code block.', max_length=3000, null=True),
        ),
    ]
