partidos_mix = {u'DC': 4,
                u'DEM': 12,
                u'SOLIDARIEDADE': 13,
                u'PCB': 33,
                u'PATRI': 29,
                u'AVANTE': 27,
                u'PR': 3,
                u'PP': 0,
                u'PV': 24,
                u'PT': 20,
                u'PRB': 21,
                u'MDB': 6,
                u'PODE': 14,
                u'PTC': 28,
                u'PTB': 19,
                u'PPL': 25,
                u'PPS': 23,
                u'PRP': 9,
                u'PMB': 17,
                u'PMN': 18,
                u'PSDB': 7,
                u'PDT': 11,
                u'PRTB': 5,
                u'REDE': 15,
                u'NOVO': 32,
                u'PSTU': 31,
                u'PSL': 22,
                u'PSB': 10,
                u'PSC': 2,
                u'PROS': 26,
                u'PSD': 8,
                u'PC do B': 30,
                u'PHS': 1,
                u'PSOL': 16,
                u'PCO': 34}

