partidos_mix = {"AVANTE": 0,
                "PP": 1,
                "PHS": 2,
                "PSC": 3,
                "PR": 4,
                "True": 5,
                "PT": 6,
                "REDE": 7,
                "PTC": 8,
                "PMB": 9,
                 "PDT": 10,
                 "PPS": 11,
                 "PROS": 12,
                 "PSB": 13,
                 "PV": 14,
                 "PATRI": 15,
                 "PODE": 16,
                 "PSL": 17,
                 "DC": 18,
                 "SOLIDARIEDADE": 19,
                 "PSDB": 20,
                 "PTB": 21,
                 "PRB": 22,
                 "MDB": 23,
                 "PRTB": 24,
                 "PRP": 25,
                 "DEM": 26,
                 "PMN": 27,
                 "PC do B": 28,
                 "PCB": 29,
                 "PPL": 30,
                 "PSTU": 31,
                 "PCO": 32,
                 "PSD": 33,
                 "PSOL": 34,
                 "NOVO": 35}

