# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-22 22:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('popular_proposal', '0033_popular_proposal_multiple_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeRepresentaCommitment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('popular_proposal.commitment',),
        ),
        migrations.CreateModel(
            name='MeRepresentaPopularProposal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('popular_proposal.popularproposal',),
            managers=[
                ('ordered', django.db.models.manager.Manager()),
            ],
        ),
    ]
