# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-17 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0032_auto_20180525_1552'),
        ('merepresenta', '0002_auto_20180717_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elections.Candidate')),
                ('cpf', models.CharField(max_length=1024, null=True)),
                ('nome_completo', models.CharField(max_length=1024, null=True)),
                ('numero', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('elections.candidate',),
        ),
        migrations.AlterField(
            model_name=b'VolunteerGetsCandidateEmailLog',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merepresenta.Candidate'),
        ),
        migrations.AlterField(
            model_name=b'VolunteerInCandidate',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merepresenta.Candidate'),
        ),
    ]
