# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-18 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merepresenta', '0003_auto_20180717_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaligacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, null=True)),
                ('initials', models.CharField(max_length=1024, null=True)),
                ('number', models.CharField(max_length=1024, null=True)),
                ('mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, null=True)),
                ('initials', models.CharField(max_length=1024, null=True)),
                ('number', models.CharField(max_length=1024, null=True)),
                ('mark', models.IntegerField()),
                ('coaligacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merepresenta.Coaligacao')),
            ],
        ),
    ]
