# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-18 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merepresenta', '0005_auto_20180718_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email_repeated',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='candidate',
            name='original_email',
            field=models.EmailField(max_length=1024, null=True),
        ),
    ]
