# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-19 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merepresenta', '0006_auto_20180718_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='partido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merepresenta.Partido'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='coaligacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merepresenta.Coaligacao'),
        ),
    ]
