# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merepresenta', '0007_auto_20180719_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_ghost',
            field=models.BooleanField(default=False),
        ),
    ]
