# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-27 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merepresenta', '0008_candidate_is_ghost'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='facebook_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
