# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-31 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merepresenta', '0011_auto_20180731_1604'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='volunteerprofile',
            table='voluntarios_profile',
        ),
    ]
