# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-31 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merepresenta', '0012_auto_20180731_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='data_de_nascimento',
            field=models.DateField(null=True),
        ),
    ]
