# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merepresenta', '0013_candidate_data_de_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cpf',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
