# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0033_auto_20180717_2345'),
        ('merepresenta', '0014_auto_20180801_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateQuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merepresenta.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('elections.questioncategory',),
        ),
        migrations.AddField(
            model_name='candidatequestioncategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merepresenta.QuestionCategory'),
        ),
    ]
