# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-09 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merepresenta', '0015_auto_20180807_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='amarela',
            field=models.BooleanField(default=False, verbose_name='Amarela'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='branca',
            field=models.BooleanField(default=False, verbose_name='Branca'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidatura_coletiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='indigena',
            field=models.BooleanField(default=False, verbose_name='Ind\xedgena'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='lgbt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parda',
            field=models.BooleanField(default=False, verbose_name='Parda'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preta',
            field=models.BooleanField(default=False, verbose_name='Preta'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='renovacao_politica',
            field=models.CharField(default='', max_length=512),
        ),
    ]
