# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-30 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merepresenta', '0017_auto_20180815_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lgbt_desc',
            field=models.ManyToManyField(blank=True, to='merepresenta.LGBTQDescription'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='renovacao_politica',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
