# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-05 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merepresenta', '0019_rightanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='mark',
            field=models.FloatField(null=True),
        ),
    ]
