# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-05 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merepresenta', '0020_auto_20180905_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaligacao',
            name='mark',
        ),
    ]
