# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-01 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0034_auto_20180903_1614'),
        ('merepresenta', '0021_remove_coaligacao_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaligacao',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coligacoes', to='elections.Area'),
        ),
    ]
