# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-01 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merepresenta', '0022_coaligacao_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaligacao',
            name='classification',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
