# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-02 23:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('popular_proposal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='popular_proposal.Commitment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_args', picklefield.fields.PickledObjectField(editable=False)),
                ('search_params', picklefield.fields.PickledObjectField(editable=False)),
                ('filter_class_module', models.CharField(max_length=254)),
                ('filter_class_name', models.CharField(max_length=254)),
                ('oftenity', models.DurationField(help_text='Cada cuanto te notificamos?')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
