# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 15:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsubscription',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='searchsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
