# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_subscriptions', '0002_auto_20170704_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchsubscription',
            name='oftenity',
            field=models.DurationField(help_text='Cada cuanto te notificamos?'),
        ),
    ]
