# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 16:46
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import djchoices.choices
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('popolo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTemporaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('rejected', models.BooleanField(default=False)),
                ('rejected_reason', models.TextField()),
                ('comments', picklefield.fields.PickledObjectField(editable=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_proposals', to='popolo.Area')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_proposals', to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('in_our_side', b'InOurSide')], default='in_our_side', max_length=16, validators=[djchoices.choices.ChoicesValidator({'in_our_side': b'InOurSide'})])),
            ],
        ),
        migrations.CreateModel(
            name='PopularProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='popolo.Area')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelManagers(
            name='proposaltemporarydata',
            managers=[
                ('needing_moderation', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='proposaltemporarydata',
            name='status',
            field=models.CharField(choices=[('in_our_side', b'InOurSide'), ('in_their_side', b'InTheirSide'), ('rejected', b'Rejected')], default='in_our_side', max_length=16, validators=[djchoices.choices.ChoicesValidator({'in_our_side': b'InOurSide', 'in_their_side': b'InTheirSide', 'rejected': b'Rejected'})]),
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='temporary',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_proposal', to='popular_proposal.ProposalTemporaryData'),
        ),
        migrations.AlterField(
            model_name='proposaltemporarydata',
            name='status',
            field=models.CharField(choices=[('in_our_side', b'InOurSide'), ('in_their_side', b'InTheirSide'), ('rejected', b'Rejected'), ('accepted', b'Accepted')], default='in_our_side', max_length=16, validators=[djchoices.choices.ChoicesValidator({'accepted': b'Accepted', 'in_our_side': b'InOurSide', 'in_their_side': b'InTheirSide', 'rejected': b'Rejected'})]),
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ProposalLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popular_proposal.PopularProposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('proposal_like', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='popular_proposal.ProposalLike')),
            ],
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='likers',
            field=models.ManyToManyField(through='popular_proposal.ProposalLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposaltemporarydata',
            name='overall_comments',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='proposaltemporarydata',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='popolo.Organization')),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('popolo.organization',),
        ),
        migrations.AddField(
            model_name='proposaltemporarydata',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_proposals', to='popular_proposal.Organization'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='popular_proposal.Organization'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popular_proposals', to='popular_proposal.Organization'),
        ),
    ]
