# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-02 23:57
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import djchoices.choices
import picklefield.fields
import popular_proposal.models
import votai_utils.open_graph


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=12288, null=True)),
                ('commited', models.NullBooleanField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='elections.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='PopularProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('join_advocacy_url', models.URLField(blank=True, null=True)),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('background', models.TextField(blank=True, help_text='Antecedentes sobre tu propuesta', null=True)),
                ('contact_details', models.TextField(blank=True, help_text='\xbfC\xf3mo te pueden contactar? Esta informaci\xf3n es p\xfablica.', null=True)),
                ('document', models.FileField(blank=True, help_text='\xbfTienes alg\xfan documento para complementar tu propuesta?', null=True, upload_to='uploads/proposal/backgrounds/%Y/%m/%d/')),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='proposals/image/')),
                ('clasification', models.CharField(blank=True, max_length=255, null=True)),
                ('for_all_areas', models.BooleanField(default=False)),
                ('is_local_meeting', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('important_within_organization', models.BooleanField(default=False)),
                ('one_liner', models.CharField(blank=True, default='', max_length=140)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='elections.Area')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('generated_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals_generated_here', to='elections.Area')),
            ],
            options={
                'ordering': ['-featured', 'for_all_areas', '-created'],
                'verbose_name': 'Propuesta Ciudadana',
                'verbose_name_plural': 'Propuestas Ciudadanas',
            },
            bases=(models.Model, votai_utils.open_graph.OGPMixin),
            managers=[
                ('ordered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PopularProposalSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popular_proposal.PopularProposal')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Quieres decirle algo?', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popular_proposal.PopularProposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apoyo',
                'verbose_name_plural': 'Apoyos',
            },
        ),
        migrations.CreateModel(
            name='ProposalTemporaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_advocacy_url', models.URLField(blank=True, null=True)),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('rejected', models.BooleanField(default=False)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('comments', picklefield.fields.PickledObjectField(editable=False)),
                ('status', models.CharField(choices=[('in_our_side', b'InOurSide'), ('in_their_side', b'InTheirSide'), ('rejected', b'Rejected'), ('accepted', b'Accepted')], default='in_our_side', max_length=16, validators=[djchoices.choices.ChoicesValidator({'accepted': b'Accepted', 'in_our_side': b'InOurSide', 'in_their_side': b'InTheirSide', 'rejected': b'Rejected'})])),
                ('overall_comments', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('is_local_meeting', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_proposals', to='elections.Area')),
                ('generated_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.Area')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, popular_proposal.models.ProposalCreationMixin),
            managers=[
                ('needing_moderation', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='likers',
            field=models.ManyToManyField(through='popular_proposal.ProposalLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='sites',
            field=models.ManyToManyField(related_name='proposals', through='popular_proposal.PopularProposalSite', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='temporary',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_proposal', to='popular_proposal.ProposalTemporaryData'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='popular_proposal.PopularProposal'),
        ),
    ]
