# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaltemporarydata',
            name='status',
            field=models.CharField(choices=[('in_our_side', b'InOurSide')], default='in_our_side', max_length=16, validators=[djchoices.choices.ChoicesValidator({'in_our_side': b'InOurSide'})]),
        ),
    ]
