# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import djchoices.choices
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('popolo', '0001_initial'),
        ('popular_proposal', '0002_proposaltemporarydata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='popolo.Area')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelManagers(
            name='proposaltemporarydata',
            managers=[
                ('needing_moderation', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='proposaltemporarydata',
            name='status',
            field=models.CharField(choices=[('in_our_side', b'InOurSide'), ('in_their_side', b'InTheirSide'), ('rejected', b'Rejected')], default='in_our_side', max_length=16, validators=[djchoices.choices.ChoicesValidator({'in_our_side': b'InOurSide', 'in_their_side': b'InTheirSide', 'rejected': b'Rejected'})]),
        ),
    ]
