# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-05 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0002_auto_20160624_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='proposals/image/'),
        ),
    ]
