# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-08 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0002_auto_20160311_1609'),
        ('popular_proposal', '0003_auto_20160705_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_ptr',
        ),
        migrations.RemoveField(
            model_name='popularproposal',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='proposaltemporarydata',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
