# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0004_auto_20160406_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
