# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-08 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0004_auto_20160708_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
