# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_citizen', '0003_auto_20160712_1722'),
        ('popular_proposal', '0005_auto_20160708_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popular_proposals', to='backend_citizen.Organization'),
        ),
        migrations.AddField(
            model_name='proposaltemporarydata',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_proposals', to='backend_citizen.Organization'),
        ),
    ]
