# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('popular_proposal', '0006_proposallike_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='likers',
            field=models.ManyToManyField(through='popular_proposal.ProposalLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
