# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-28 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0006_auto_20160712_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='clasification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
