# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0007_popularproposal_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaltemporarydata',
            name='overall_comments',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
