# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-25 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0008_commitment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='proposal_like',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
