# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 20:56
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0008_proposaltemporarydata_overall_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique=True),
        ),
    ]
