# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 21:17
from __future__ import unicode_literals

from django.db import migrations


def gen_slug(apps, schema_editor):
    PopularProposal = apps.get_model('popular_proposal', 'PopularProposal')
    counter = 0
    for popular_proposal in PopularProposal.objects.all():
        counter += 1
        popular_proposal.slug = 'proposal_{:d}'.format(counter)
        popular_proposal.save()

class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0009_popularproposal_slug'),
    ]

    operations = [
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop),
    ]
