# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0012_auto_20160906_1622'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='popularproposal',
            managers=[
                ('ordered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='contact_details',
            field=models.TextField(blank=True, help_text='\xbfC\xf3mo te puede contactar un candidato?', null=True),
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='document',
            field=models.FileField(blank=True, help_text='\xbfTienes alg\xfan documento para complementar tu propuesta?', null=True, upload_to='uploads/proposal/backgrounds/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='popularproposal',
            name='background',
            field=models.TextField(blank=True, help_text='Antecedentes sobre tu propuesta', null=True),
        ),
    ]
