# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0013_auto_20160426_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popular_proposals', to='popular_proposal.Organization'),
        ),
    ]
