# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0013_auto_20160907_1410'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='popularproposal',
            managers=[
                ('ordered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='popularproposal',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='elections.Area'),
        ),
        migrations.AlterField(
            model_name='proposaltemporarydata',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_proposals', to='elections.Area'),
        ),
    ]
