# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0015_auto_20160907_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='detail',
            field=models.CharField(blank=True, max_length=12288, null=True),
        ),
    ]
