# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0016_auto_20160915_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaltemporarydata',
            name='join_advocacy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popularproposal',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='elections.Area'),
        ),
        migrations.AlterField(
            model_name='proposaltemporarydata',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_proposals', to='elections.Area'),
        ),
    ]
