# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0016_auto_20160915_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaltemporarydata',
            name='join_advocacy_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
