# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0017_auto_20170529_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='join_advocacy_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
