# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0019_popularproposal_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='is_local_meeting',
            field=models.BooleanField(default=False),
        ),
    ]
