# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 23:13
from __future__ import unicode_literals

from django.db import migrations
from constance import config


def create_areas(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0020_popularproposal_is_local_meeting'),
    ]

    operations = [
         migrations.RunPython(create_areas),
    ]
