# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0021_auto_20170607_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposallike',
            name='message',
            field=models.TextField(blank=True, help_text='Quieres decirle algo?', null=True),
        ),
        migrations.AlterField(
            model_name='popularproposal',
            name='contact_details',
            field=models.TextField(blank=True, help_text='\xbfC\xf3mo te pueden contactar? Esta informaci\xf3n es p\xfablica.', null=True),
        ),
    ]
