# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0029_candidate_has_won'),
        ('popular_proposal', '0022_auto_20170612_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaltemporarydata',
            name='generated_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.Area'),
        ),
        migrations.AddField(
            model_name='proposaltemporarydata',
            name='is_local_meeting',
            field=models.BooleanField(default=False),
        ),
    ]
