# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0023_auto_20170711_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularproposal',
            options={'ordering': ['for_all_areas', '-created'], 'verbose_name': 'Propuesta Ciudadana', 'verbose_name_plural': 'Propuestas Ciudadanas'},
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proposallike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
