# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('popular_proposal', '0024_auto_20170720_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
