# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 22:35
from __future__ import unicode_literals

from django.db import migrations


def add_content_types_to_proposals(apps, schema_editor):
    from popular_proposal.models import PopularProposal
    from django.contrib.contenttypes.models import ContentType
    content_type = ContentType.objects.get_for_model(PopularProposal)
    for p in PopularProposal.objects.all():
        p.content_type = content_type
        if not p.data:
            p.data = {}
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0025_popularproposal_content_type'),
    ]

    operations = [
        migrations.RunPython(add_content_types_to_proposals),
    ]
