# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0025_popularproposal_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
