# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0026_popularproposal_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularproposal',
            options={'ordering': ['-featured', 'for_all_areas', '-created'], 'verbose_name': 'Propuesta Ciudadana', 'verbose_name_plural': 'Propuestas Ciudadanas'},
        ),
        migrations.AlterModelOptions(
            name='proposallike',
            options={'verbose_name': 'Apoyo', 'verbose_name_plural': 'Apoyos'},
        ),
    ]
