# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0027_auto_20170914_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
