# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0028_popularproposal_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularproposal',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
