# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0029_auto_20171025_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='important_within_organization',
            field=models.BooleanField(default=False),
        ),
    ]
