# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0030_popularproposal_important_within_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproposal',
            name='one_liner',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
