# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0031_popularproposal_one_liner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitment',
            old_name='candidate',
            new_name='authority',
        ),
    ]
