# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-19 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('popular_proposal', '0032_auto_20180308_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularProposalSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popular_proposal.PopularProposal')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.AddField(
            model_name='popularproposal',
            name='sites',
            field=models.ManyToManyField(related_name='proposals', through='popular_proposal.PopularProposalSite', to='sites.Site'),
        ),
    ]
