# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0032_auto_20180201_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularproposal',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popularproposals', to='elections.Area'),
        ),
        migrations.AlterField(
            model_name='popularproposal',
            name='generated_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popularproposals_generated_here', to='elections.Area'),
        ),
        migrations.AlterField(
            model_name='popularproposal',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popularproposals', to='backend_citizen.Organization'),
        ),
        migrations.AlterField(
            model_name='popularproposal',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popularproposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposaltemporarydata',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposaltemporarydatas', to='elections.Area'),
        ),
        migrations.AlterField(
            model_name='proposaltemporarydata',
            name='generated_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposaltemporarydatas_generated_here', to='elections.Area'),
        ),
        migrations.AlterField(
            model_name='proposaltemporarydata',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposaltemporarydatas', to='backend_citizen.Organization'),
        ),
        migrations.AlterField(
            model_name='proposaltemporarydata',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposaltemporarydatas', to=settings.AUTH_USER_MODEL),
        ),
    ]
