# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0033_auto_20180207_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularproposal',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='proposaltemporarydata',
            name='organization',
        ),
    ]
