# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_proposal', '0034_auto_20180207_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularproposal',
            options={'ordering': ['-featured', '-created'], 'verbose_name': 'Propuesta Ciudadana', 'verbose_name_plural': 'Propuestas Ciudadanas'},
        ),
        migrations.AddField(
            model_name='proposaltemporarydata',
            name='for_all_areas',
            field=models.BooleanField(default=False),
        ),
    ]
