# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('popular_proposal', '0024_auto_20170720_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsProposal',
            fields=[
                ('popularproposal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='popular_proposal.PopularProposal')),
            ],
            bases=('popular_proposal.popularproposal',),
        ),
    ]
