# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 22:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('popular_proposal', '0026_auto_20170802_2235'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsGathering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Nombre del encuentro')),
                ('stats_data', picklefield.fields.PickledObjectField(editable=False)),
                ('presidents_features', multiselectfield.db.fields.MultiSelectField(choices=[('Habilidades intelectuales', (('inteligente', 'Inteligente'), ('creativo', 'Creativo/a'), ('objetivo', 'Objetivo'), ('con_iniciativa', 'Con Iniciativa'), ('profesional', 'Profesional'), ('culto', 'Culto/a'), ('bilingue', 'Biling\xfce'))), ('Valores', (('responsable', 'Responsable'), ('transparente', 'Transparente'), ('honesto', 'Honesto/a'), ('equitativo', 'Equitativo/a'), ('justo', 'Justo/a'), ('comprometido', 'Comprometido/a'))), ('Habilidades personales', (('integrador', 'Integrador/a'), ('motivador', 'Motivador/a'), ('abierto', 'Abierto/a a escuchar'), ('accesible', 'Accesible'), ('empatico', 'Emp\xe1tico/a'), ('confiable', 'Confiable'))), ('Habilidades de rol', (('lider', 'Lider'), ('administrador', 'Buen Administrador/a'), ('negociante', 'Buen Negociante'), ('comunicador', 'Buen Comunicador/a'), ('influyente', 'Influyente'), ('eficiente', 'Eficiente'), ('experiencia', 'Con experiencia')))], max_length=512, null=True, verbose_name='Caracter\xedsticas de un buen presidente')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='votita/images/', verbose_name='Foto del encuentro')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KidsProposal',
            fields=[
                ('popularproposal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='popular_proposal.PopularProposal')),
                ('gathering', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='votita.KidsGathering')),
            ],
            bases=('popular_proposal.popularproposal',),
        ),
    ]
