# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('votita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsGathering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stats_data', picklefield.fields.PickledObjectField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='kidsproposal',
            name='gathering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='votita.KidsGathering'),
        ),
    ]
