# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0029_candidate_has_won'),
        ('votita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidsgathering',
            name='generated_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.Area'),
        ),
    ]
