# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 16:31
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('votita', '0002_auto_20170728_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidsgathering',
            name='presidents_features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Habilidades intelectuales', (('ingeligente', 'Inteligente'), ('honesto', 'Honesto'))), ('Valores', (('responsabilidad', 'Responsabilidad'), ('transparencia', 'Transparencia')))], max_length=64, null=True),
        ),
    ]
