# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votita', '0003_auto_20170811_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidsgathering',
            name='comments',
            field=models.TextField(blank=True, default='', help_text='\xbfC\xf3mo podemos empoderar mejor a nuestros ni\xf1os?', verbose_name='\xbfTienes alg\xfan comentario sobre la actividad?'),
        ),
    ]
