# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('votita', '0003_kidsgathering_presidents_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidsgathering',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='votita/images/'),
        ),
        migrations.AlterField(
            model_name='kidsgathering',
            name='presidents_features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Habilidades intelectuales', (('inteligente', 'Inteligente'), ('honesto', 'Honesto'))), ('Valores', (('responsabilidad', 'Responsabilidad'), ('transparencia', 'Transparencia')))], max_length=64, null=True),
        ),
    ]
