# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-03 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('votita', '0004_kidsgathering_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kidsgathering',
            options={'verbose_name': 'Encuentro', 'verbose_name_plural': 'Encuentros'},
        ),
        migrations.AlterModelOptions(
            name='kidsproposal',
            options={'verbose_name': 'Medida', 'verbose_name_plural': 'Medidas'},
        ),
        migrations.AddField(
            model_name='kidsgathering',
            name='school',
            field=models.CharField(blank=True, max_length=512, verbose_name='Establecimiento u organizaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='kidsgathering',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='\xbfC\xf3mo podemos empoderar mejor a nuestros ni\xf1os?'),
        ),
        migrations.AlterField(
            model_name='kidsgathering',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='votita/images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='kidsgathering',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Grupo de participantes'),
        ),
        migrations.AlterField(
            model_name='kidsgathering',
            name='presidents_features',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name=''),
        ),
    ]
