# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-02 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Candidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidacyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('times_email_has_been_sent', models.IntegerField(default=0)),
                ('used_by_candidate', models.BooleanField(default=False)),
                ('identifier', models.UUIDField(default=uuid.uuid4)),
                ('initial_password', models.CharField(blank=True, max_length=255)),
                ('candidacy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_candidate.Candidacy')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='elections.Candidate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidacy_contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
