# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_candidate', '0003_auto_20160801_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidacycontact',
            name='initial_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
