# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-23 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_candidate', '0005_auto_20171005_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsuggestionforincremental',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
