# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-23 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_candidate', '0007_candidateincremental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalsuggestionforincremental',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
