# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_candidate', '0008_auto_20171023_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incrementalscandidatefilter',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
