# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_candidate', '0010_candidateincremental_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateincremental',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateincremental',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
