# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_candidate', '0011_auto_20171026_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateincremental',
            name='suggestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_candidate.IncrementalsCandidateFilter'),
        ),
    ]
