# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-17 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_candidate', '0012_auto_20171026_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='incrementalscandidatefilter',
            name='subject',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='candidateincremental',
            name='suggestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_candidate.IncrementalsCandidateFilter'),
        ),
    ]
