# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-14 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_candidate', '0014_remove_suggesting_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidacycontact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidacy_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
