# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-02 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlconf', models.CharField(max_length=512)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_site', to='sites.Site')),
            ],
        ),
    ]
