# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-02 23:56
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('title', models.CharField(max_length=512, verbose_name='T\xedtulo')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('logo', models.ImageField(blank=True, help_text='perrito', null=True, upload_to='organizations/profiles/', verbose_name='El logo de tu organizaci\xf3n')),
                ('logo_small', models.ImageField(blank=True, null=True, upload_to='organizations/profiles_small/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='organizations/backgrounds/', verbose_name='Imagen de fondo')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='T\xedtulo de tu organizaci\xf3n')),
                ('sub_title', models.TextField(blank=True, null=True, verbose_name='Bajada')),
                ('org_url', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#CCDDCC', max_length=8, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#2DDC22', max_length=8, verbose_name='Color secundario')),
                ('rss_url', models.URLField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_template', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='extrapage',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_pages', to='organization_profiles.OrganizationTemplate'),
        ),
    ]
