# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtemplate',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/backgrounds/', verbose_name='Imagen de fondo'),
        ),
        migrations.AddField(
            model_name='organizationtemplate',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationtemplate',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationtemplate',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/profiles/', verbose_name='El logo de tu organizaci\xf3n'),
        ),
        migrations.AddField(
            model_name='organizationtemplate',
            name='org_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationtemplate',
            name='primary_color',
            field=models.CharField(default='#CCDDCC', max_length=8, verbose_name='Color primario'),
        ),
        migrations.AddField(
            model_name='organizationtemplate',
            name='rss_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationtemplate',
            name='secondary_color',
            field=models.CharField(default='#DDCCDD', max_length=8, verbose_name='Color secundario'),
        ),
        migrations.AddField(
            model_name='organizationtemplate',
            name='sub_title',
            field=models.TextField(blank=True, null=True, verbose_name='Bajada'),
        ),
        migrations.AddField(
            model_name='organizationtemplate',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='T\xedtulo de tu organizaci\xf3n'),
        ),
        migrations.AddField(
            model_name='organizationtemplate',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
