# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 21:10
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_profiles', '0002_auto_20170512_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('title', models.CharField(max_length=512, verbose_name='T\xedtulo')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_pages', to='organization_profiles.OrganizationTemplate')),
            ],
        ),
    ]
