# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 23:28
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

def create_extra_pages(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    OrganizationTemplate = apps.get_model('organization_profiles', 'OrganizationTemplate')
    ExtraPage = apps.get_model('organization_profiles', 'ExtraPage')
    for template in OrganizationTemplate.objects.all():
        for data in settings.DEFAULT_EXTRAPAGES_FOR_ORGANIZATIONS:
            ExtraPage.objects.create(template=template,
                                     title=data["title"],
                                     content=data["content"])

class Migration(migrations.Migration):

    dependencies = [
        ('organization_profiles', '0003_extrapage'),
    ]

    operations = [
        migrations.RunPython(create_extra_pages),
    ]
