# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0002_auto_20160311_1609'),
        ('preguntales', '0002_messageconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=uuid.uuid4, max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_identifiers', to='preguntales.Message')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popolo.Person')),
            ],
        ),
    ]
