# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import preguntales.models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntales', '0004_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='preguntales.Message'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='elections.Candidate'),
        ),
        migrations.AlterField(
            model_name='message',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='elections.Election'),
        ),
        migrations.AlterField(
            model_name='messageconfirmation',
            name='key',
            field=models.CharField(default=preguntales.models.uuid_with_no_dashes, max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='key',
            field=models.CharField(default=preguntales.models.uuid_with_no_dashes, max_length=255),
        ),
    ]
