# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntales', '0005_auto_20160421_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content',
            field=models.FileField(max_length=255, upload_to=b'attachments/%Y/%m/%d'),
        ),
    ]
